name: agent_push
on:
  push:
    branches: [agent/codex]
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -c constraints.txt
          pip install pip-audit
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Node dependencies
        run: npm ci
      - name: Run linters
        run: |
          ruff check .
          npm run lint
      - name: Run tests
        run: |
          pytest -q
          pip-audit -r requirements.txt -c constraints.txt
          npm test
      - name: Build container
        run: |
          docker build -t license-issuer:${{ github.sha }} .
      - name: Diff README and AGENTS
        run: |
          git --no-pager diff origin/main -- README.md AGENTS.md || true
